name: smart_hydronest
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  device_preview: ^1.2.0
  http: ^0.13.6
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  provider: ^6.1.5
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.6
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0
  mqtt_client: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/slider_suhu.png
    - assets/images/slider_cahaya.png
    - assets/images/logo.png
    - assets/images/profil.jpg
