// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqQgDTcWX_zQOEyA1Xlg3puKo-tzSwqqk',
    appId: '1:323425329851:android:04a9aed2e66dee65d93f9e',
    messagingSenderId: '323425329851',
    projectId: 'smart-hydronest',
    storageBucket: 'smart-hydronest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8CkNWA2-nSToecWR8R9z8-HrXYLlyZAQ',
    appId: '1:323425329851:ios:db8ec0e2b4a3a77ad93f9e',
    messagingSenderId: '323425329851',
    projectId: 'smart-hydronest',
    storageBucket: 'smart-hydronest.firebasestorage.app',
    iosBundleId: 'com.example.smartHydronest',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNAxF0_8UMp_D-dSDyZwvlPnbfTYY9Ygk',
    appId: '1:323425329851:web:afb65a97052a1729d93f9e',
    messagingSenderId: '323425329851',
    projectId: 'smart-hydronest',
    authDomain: 'smart-hydronest.firebaseapp.com',
    storageBucket: 'smart-hydronest.firebasestorage.app',
    measurementId: 'G-CY6Q89ZLGR',
  );

}